net-snmp: fix net-snmp do_compile fail with openssl-no-weak-ciphers
Issue: LIN1019-748

* when enable openssl-no-weak-ciphers, net-snmp need to configure with
--disable-des, or it will met error like:

scapi.c:1180:5: error: unknown type name 'DES_key_schedule'

* move PACKAGECONFIG into template.conf, and remove useless
  bbappend

Signed-off-by: Changqing Li <changqing.li@windriver.com>