feature/tpm2: remove no-ec from openssl-no-weak-ciphers
Since tpm2-tss_2.2.3.bb -> tpm2-tss_2.3.2.bb, it requres openssl
enable ec, otherwise the build failed with:
...
error: unknown type name 'EC_GROUP'
...

Then remove no-ec from WEAKCIPHERS

Issue: LINUXEXEC-8397

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>