nagios: updates to fix builds
Issue: TA194345

With the advent of recipe specific sysroots (RSS) there were several
changes in the build behavior that prevent the various nagios recipes
from properly building (currently failing with "unknown user
nagios"). Before RSS user creation in the -core recipe would be
available when the other nagios-* recipes would build (in most cases),
we must now ensure this user creation is done in all recipes which
need the nagios user and group, so moved to nagios-common.inc.

Similarly we must ensure directories have consistent ownership/perms
for the various nagios recipes, we make use of the
FILESYSTEM_PERMS_TABLES functionality to ensure this consistency. This
will prevent seeing errors such as

  Error: Transaction check error:
   file /etc/nagios conflicts between attempted installs of \
     nagios-nsca-daemon-2.9.1-r0.core2_64 \
     and nagios-nrpe-plugin-2.15-r0.core2_64

during rootfs assembly.

Due to an incompatability with OpenSSL we also disable ssl support to
resolve a build failure:

   undefined reference to `get_dh512'

per the discussion here:
https://www.linuxquestions.org/questions/linux-software-2/nagios-nrpe-undefined-reference-to-%60get_dh512%27-613815/

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>