Revert "ovp: qemu: Fix execute virsh qemu-monitor-command error"
Issue: LINCD-2956

This reverts commit 3cd3dedb307636e7905eeec3eadb5d35023171e6
when qemu config add "--enable-profiler" option, compiling
machines is "qemux86" ovp guest image, qemu do_compile failed.

"qemu-5.1.0/include/qemu/compiler.h:93:36: error: static assertion failed:
"not expecting: sizeof(*&prof->table_op_count[opc]) > ATOMIC_REG_SIZE"
93 | #define QEMU_BUILD_BUG_MSG(x, msg) _Static_assert(!(x), msg)"

Signed-off-by: Zhang Qiang <qiang.zhang@windriver.com>