image-export-vars.bbclass: rename to image_export_vars.bbclass
Fixed:
ERROR: The classname image-export-vars contains a dash character and is
calling an sh function image-export-vars_ouput_image_vars using
EXPORT_FUNCTIONS. Since a dash is illegal in sh function names, this
cannot work, please rename the class or don't use EXPORT_FUNCTIONS.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>