wrlinux-image-minimal-initramfs: add MLPREFIX to wrlinux-image-minimal-initramfs
Issue: LIN10-3454

The 32bit wrlinux-image-minimal-initramfs should be built when build lib32-iso, e.g.:
MACHINE = "qemux86-64"
require conf/multilib.conf
MULTILIBS = "multilib:lib32"
DEFAULTTUNE_virtclass-multilib-lib32 = "x86"
IMAGE_FSTYPES += "iso"

$ bitbake lib32-wrlinux-image-glibc-std
Exception: FileExistsError: [Errno 17] File exists: '/path/to/tmp/sysroots-components/core2-64/qemuwrapper-cross/usr/bin/crossscripts/qemuwrapper' -> '/path/to/tmp/work/qemux86_64-pokymllib32-linux/lib32-wrlinux-image-glibc-std/1.0-r0/lib32-recipe-sysroot/usr/bin/crossscripts/qemuwrapper'

This was because:
lib32-wrlinux-image-glibc-std -> wrlinux-image-minimal-initramfs
wrlinux-image-minimal-initramfs -> qemuwrapper-cross
lib32-wrlinux-image-glibc-std -> lib32-qemuwrapper-cross

So we got the error, build lib32-wrlinux-image-minimal-initramfs can fix the problem.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>