saftest: improve reproducibility
The file build_log in package saftest contains host paths, the root
cause is there are build failures log recorded in the build_log.

So fix the build failure could improve saftest reproducibility

- Add `-lpthread' to CFLAGS to fix linker error
|undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'

- Use the latest openhpi SaHpi.h to replace the obsolete one
  of saftest

Issue: LIN1018-2513

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>