linux-yocto-dev.bbappend: Remove it for LTS21
Issue: LINUXEXEC-12820

Fixed:
DISTRO = "wrlinux-ovp"
$ bitbake -p
bb.data_smart.ExpansionError: Failure expanding variable SRCPV

This is because LTS21 doesn't have a local source for linux-yocto-dev, LTS21
doesn't support the next config, so just remove it to fix the error.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>