ceph: fix build with boost 1.68
Issue: LIN1018-2340

ceph 9.2.0 will have compile failure with boost 1.68 like below.

  error: no matching function for call to 'boost::date_time::subsecond_duration
  <boost::posix_time::time_duration, 1000000>::subsecond_duration(float)'

This is due to boost 1.68 does not do implicit type casting and
hence requires doing it explicitly.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>