ceph: workaround to build ceph with gcc8
Issue: LIN1018-2340

gcc-8 uses stricter checkings than previous gcc. In particular,
ceph 9.2.0 will fail to compile with the following error message.

  error: static assertion failed: comparison object must be invocable with two arguments of key type
         static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},

So we define static_assert to be empty as a workaround so that
ceph could compile correctly with gcc8.

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>