wr-common-packages-native: fix error Missing or unbuildable dependency chain: ['wr-common-packages-native', 'update-rc']
Issue: LIN1019-3394

With "Building Native Tools" section steps, we get the the following error
info:

$ eval `bitbake -e $recipe | grep -e '^SSTATE_DIR=' -e '^B='`
ERROR: Nothing PROVIDES 'glib-2' (but /buildarea1/lwang4/19rcpl/std/layers/
wrlinux/recipes-base/wr-common-packages-native/wr-common-packages-native.bb
DEPENDS on or otherwise requires it). Close matches:
  glib-2.0
  glibc
ERROR: Nothing PROVIDES 'update-rc' (but /buildarea1/lwang4/19rcpl/std/layers/
wrlinux/recipes-base/wr-common-packages-native/wr-common-packages-native.bb
DEPENDS on or otherwise requires it). Close matches:
  update-rc.d
ERROR: Nothing PROVIDES 'glib-2' (but /buildarea1/lwang4/19rcpl/std/layers/
wrlinux/recipes-base/wr-common-packages-native/wr-common-packages-native.bb
DEPENDS on or otherwise requires it). Close matches:
  glib-2.0
  glibc
ERROR: Nothing PROVIDES 'update-rc' (but /buildarea1/lwang4/19rcpl/std/layers/
wrlinux/recipes-base/wr-common-packages-native/wr-common-packages-native.bb
DEPENDS on or otherwise requires it). Close matches:
  update-rc.d
ERROR: Nothing PROVIDES 'glib-2' (but /buildarea1/lwang4/19rcpl/std/layers/
wrlinux/recipes-base/wr-common-packages-native/wr-common-packages-native.bb
DEPENDS on or otherwise requires it). Close matches:
  glib-2.0
  glibc
ERROR: Nothing PROVIDES 'update-rc' (but /buildarea1/lwang4/19rcpl/std/layers/
wrlinux/recipes-base/wr-common-packages-native/wr-common-packages-native.bb
DEPENDS on or otherwise requires it). Close matches:
  update-rc.d
[lwang4@pek-lpgtest20 build]$ recipe="wr-common-packages-native" ^C
[lwang4@pek-lpgtest20 build]$ bitbake $recipe
WARNING: You have included the meta-openstack layer, but 'openstack' has
not been enabled in your DISTRO_FEATURES. Some bbappend files and preferred
version setting may not take effect. See the meta-openstack README for
details on enabling openstack support.
Loading cache: 100% |######################################| Time: 0:00:01
Loaded 8470 entries from dependency cache.
Parsing recipes: 100% |####################################| Time: 0:00:24
Parsing of 3574 .bb files complete (3572 cached, 2 parsed). 8472 targets,
6037 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing PROVIDES 'update-rc' (but /buildarea1/lwang4/19rcpl/std/layers/
wrlinux/recipes-base/wr-common-packages-native/wr-common-packages-native.bb
DEPENDS on or otherwise requires it). Close matches:
  update-rc.d
ERROR: Required build target 'wr-common-packages-native' has no buildable
providers.
Missing or unbuildable dependency chain was: ['wr-common-packages-native',
'update-rc']

Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Signed-off-by: Stefan Ghinea <stefan.ghinea@windriver.com>