template: dpdk: add the support for qemux86_64 and qemux86 back to dpdk/template.conf
Issue: LIN1019-5141

A build error was encountered  when compiling the dpdk for qemux86_64 caused
by missing the uio.ko. The commit "4757ba60" specified that only
intel_x86_64 support it, while the dpdk is compatible with qemux86_64 now in
wrlinux.

"""
ERROR: "__uio_register_device" [x86_64-native-linuxapp-gcc/build/kernel/linux/igb_uio/igb_uio.ko] undefine
ERROR: "uio_event_notify" [x86_64-native-linuxapp-gcc/build/kernel/linux/igb_uio/igb_uio.ko] undefined!
ERROR: "uio_unregister_device"[x86_64-native-linuxapp-gcc/build/kernel/linux/igb_uio/igb_uio.ko] undefine

"""

Fix: 4757ba60 (template: dpdk: add support for nxp bsps)

(LOCAL REV: NOT UPSTREAM) --not available

Signed-off-by: Liu Haitao <haitao.liu@windriver.com>