vdso-test: fix type conflict
Issue: LINUXEXEC-6161

New glibc says:
     * Remove the documentation of struct timezone.  Matching POSIX,
       say that the type of the second argument to gettimeofday and
       settimeofday is [const] void *.

So fix the type to avoid the following error.

  error: conflicting types for 'gettimeofday'

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>