scap-security-guide: fix build with Python 3.9
Issue: LINCD-3546

The getchildren and getiterator functions are deprecated in Python 3.9.
Backport 3 patches to fix the build issue.

Fixes:
File "TOPDIR/tmp-glibc/work/mips64r2-wrs-linux/scap-security-guide/0.1.45+gitAUTOINC+870a6018c3-r0/git/ssg/build_cpe.py",
line 47, in extract_referred_nodes for element in tree_with_refs.getiterator():
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'

Signed-off-by: Yi Zhao <yi.zhao@windriver.com>