wrlinux-image-initramfs: remove depends to grub-efi
Issue: LIN10-1999

wrlinux-image-initramfs should not depend on grub-efi.

The removed logic used to fix the error (LIN9-4712) which only fails
on LIN9:

  Exception: FileNotFoundError: [Errno 2] No such file or directory: \
  '.../tmp/deploy/licenses/grub-efi/recipeinfo'
  ERROR: wrlinux-image-initramfs-1.0-r0 do_image_complete: \
  Function failed: write_deploy_manifest

No such issue on LIN10 since the 'rpms/' have been moved out from
image build dir.

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>