monit 4.9: fix compile failure since openssl upgraded to 1.1.1
fix compile failure since openssl upgraded to 1.1.1

There is a compile failure since openssl upgraded to 1.1.1
[snip]
|ssl.c:822:15: error: storage size of 'found_cert' isn't known
|   X509_OBJECT found_cert;
|               ^~~~~~~~~~
|ssl.c:824:46: error: dereferencing pointer to incomplete type
'X509_STORE_CTX' {aka 'struct x509_store_ctx_st'}
|   X509_NAME_oneline(X509_get_subject_name(ctx->current_cert), subject,
[snip]

Use compatible api to support both of openssl 1.0.x and 1.1.x

Issue: LIN1018-2322

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>