vdso-test: fix do package qa error
Issue: LIN1018-2486

fix below error:
do_package_qa: QA Issue: No GNU_HASH in the elf binary:
'xxx/usr/bin/vdso_test-x86_64' [ldflags]

fix by add ${LDFLAGS}, but LDFLAGS contains -fstack-protector-strong,
will cause compile failed since undefined reference to `__stack_chk_fail',
so add -fno-stack-protector to close -fstack-protector-strong.

Signed-off-by: Changqing Li <changqing.li@windriver.com>