wrlinux: nxp-imx8: move u-boot-imx_2017.03.bb to nxp-imx8 layer
Issue: LIN10-4964

Because u-boot-imx_2017.03.bb depends on meta-freescale layer, this will
cause that all other machine bsps must contain meta-freescale or else
bitbake will throw the error as below:

ERROR: ParseError at layers/wrlinux/recipes-bsp/u-boot/u-boot-imx_2017.03.bb:21: Could not inherit file classes/fsl-u-boot-localversion.bbclass

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>