gen-image: fix handoff_dir and pr_dir incorrectly setting
When -o <outdir> is used, there is failure
...
  File "../layers/wrlinux/scripts/gen-image/gen-image", line 527, in post
    os.makedirs(self.pr_dir)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/buildarea/hjia/cbas/outdir/prserv'
...

The handoff_dir should be in outdir rather than builddir,
and pr_dir should be in handoff_dir rather than outdir

Revert previouslly fix, move old to ../

Issue: LINUXEXEC-9917

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>