libpam bbappend: drop yylex to static force
Since flex was upgraded to 2.6.4, there is a build failure
...
In file included from ../../../Linux-PAM-1.3.1/modules/pam_console/configfile.c:56:
configfile.lex.c:23:15: error: static declaration of '_pc_yylex' follows non-static declaration
   23 | #define yyleng _pc_yyleng
      |               ^~~~~~~~~
configfile.lex.c:1091:28: note: in expansion of macro 'yylex'
 1091 |
      |                            ^
configfile.lex.c:1111:1: note: in expansion of macro 'YY_DECL'
 1111 |  */
      | ^~~
configfile.lex.c:23:15: note: previous declaration of '_pc_yylex' was here
   23 | #define yyleng _pc_yyleng
      |               ^~~~~~~~~
configfile.lex.c:1089:12: note: in expansion of macro 'yylex'
 1089 |
      |            ^
...

Google the world and find a similar fix
https://lists.pld-linux.org/mailman/pipermail/pld-cvs-commit/Week-of-Mon-20170703/465181.html

Issue: LINCD-563

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>