wrlinux-image-initramfs: add grub-efi depends on x86
Issue: LIN10-3245

Add grub-efi:do_populate_lic depends for x86
to fix below error:
Exception: FileNotFoundError: [Errno 2] No such file or directory:
'../tmp-glibc/deploy/licenses/grub-efi/recipeinfo'
ERROR: wrlinux-image-initramfs-1.0-r0 do_image_complete: Function
failed: write_deploy_manifest

Signed-off-by: Mingli Yu <Mingli.Yu@windriver.com>