startup-container: add cbas to distro check
To workaround non-cbas world build failure:
...
ERROR: Nothing RPROVIDES 'docker' (but /layers/wrlinux/recipes-support/startup-container/
startup-container_1.0.bb RDEPENDS on or otherwise requires it)
...

Issue: LINUXEXEC-10230

Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>