wrlinux-whitelist.conf: change to use BPN for libx86-1
Issue: LIN9-1317

BPN is used to check and decide if the package is
in whitelist, and the BPN of the recipe libx86-1
is libx86, so use BPN in the whitelist instead or
it will fail to build for multilib:

ERROR: lib32-libx86-1 was skipped: Not supported by wrlinux

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>