ceph: fixup build error
Issue: TA194345

The current build fails with

   error: invalid Python installation: unable to open
   .../ceph/9.2.0-r0/recipe-sysroot/usr/lib64/python2.7/config/Makefile
   (No such file or directory)

I believed this is caused by things being more tightly controlled via
recipe specific sysroots, in the past python2.7 was most likely made
available by a previous package which had a DEPENDS on python. Make
the DEPENDS explicit to ensure this file is available at build time,
even with RSS.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>