linux-yocto-wrlinux.inc: update LINUX_VERSION to 4.12.14
Issue: LIN10-2326

The kernel source had been upgraded to 4.12.14:
Merge: a630dfe fa39478
Author: Bruce Ashfield <bruce.ashfield@windriver.com>
Date:   Wed Oct 18 18:32:47 2017 -0400

    Merge tag 'v4.12.14' into standard/base

    This is the 4.12.14 stable release

So update LINUX_VERSION to 4.12.14 to fix the problem:
$ bitbake linux-yocto

ERROR: Package Version (4.12.12+gitAUTOINC+73365069d8_26c1863a74) does not
match of kernel being built (4.12.14). Please update the PV variable to match
the kernel source or set KERNEL_VERSION_SANITY_SKIP="1" in your recipe.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>