wrlinux.conf: remove -fno-omit-frame-pointer on x86 for stress-ng
Issue: LINCD-2664

After stress-ng upgrade to 0.11.15, the below logic is introduced.
b9064bd0 stress-enosys: add legacy int 0x80 method of calling system calls

Fixes:
| stress-enosys.c: In function 'exercise_syscall':
| stress-enosys.c:230:1: error: bp cannot be used in 'asm' here

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Robert Yang <liezhi.yang@windriver.com>