conf/layer.conf: add meta-anaconda to LAYERRECOMMENDS_wrlinux
Issue: US117283

Fixed layerindex's "update.py -b master-wr" error:
bb.parse.ParseError: ParseError at
/path/to/wrlinux/dynamic-layers/meta-anaconda/recipes-installer/images/wrlinux-image-installer-initramfs.bb:4:
Could not include required file recipes-installer/images/core-image-anaconda-initramfs.bb

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>