wrlinux-tiny.conf: clean PACKAGECONFIG for lib32-opkg-utils
Issue: LIN8-209

Otherwise lib32-python would be built because lib32-opkg-utils depends
on it and cause build errors:

./libpython2.7.so: undefined reference to `localeconv'
./libpython2.7.so: undefined reference to `towlower'
./libpython2.7.so: undefined reference to `iswlower'
./libpython2.7.so: undefined reference to `nl_langinfo'
./libpython2.7.so: undefined reference to `iswupper'
./libpython2.7.so: undefined reference to `iswalpha'
./libpython2.7.so: undefined reference to `towupper'
./libpython2.7.so: undefined reference to `iswspace'

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>