gen-image: Move full and minimal images into BBFILES
Issue: LINUXEXEC-12764
Issue: LINUXEXEC-12765

Now gen-image supports all BSPs, hide them doesn't make much sense, move them
into BBFILES will make it easy to debug, but still limit its usage to gen-image
only, for example, when directly build it:

$ bitbake wrlinux-image-minimal
ERROR: Nothing PROVIDES 'wrlinux-image-minimal'
wrlinux-image-minimal was skipped: This recipe is highly customized for gen-image, cannot be used for any other cases

We can add "require scripts/gen-image/data/wrlinux-bin-image.conf" to
conf/local.conf to bypass the error as gen-image does.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>